version: '3'
services:
  app:
    container_name: vc-service
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ./logs:/app/dist/logs
    ports:
      - '9000:9000'
    depends_on:
      - db
  db:
    container_name: vcs-db
    image: mysql:8
    environment:
      MYSQL_DATABASE: vcs_db
      MYSQL_ROOT_PASSWORD: 0qn5tNHveRbsd047ev5QGvaWsXzCTQkF
      MYSQL_ROOT_HOST: '%'
      MYSQL_USER: admin@vcs
      MYSQL_PASSWORD: FuqLGmcDPKQV2awRbu3UBaX1ziNeBzUi
    volumes:
      - vcs_db:/var/lib/mysql
    ports:
      - '9001:3306'
    restart: always
    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp --default-authentication-plugin=mysql_native_password

volumes:
  vcs_db:
